apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: microservices
  labels:
    app: microservices
    component: security
    tier: shared
type: Opaque
stringData:
  JWT_SECRET: "myfancysecret"

---


apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret-prod
  namespace: default
  labels:
    app: microservices
    component: security
    tier: shared
    environment: production
type: Opaque
data:
  JWT_SECRET: dHUtc2VjcmV0LXN1cGVyLXNlZ3Vyby1nZW5lcmFkby1hbGVhdG9yaWFtZW50ZQ==
